/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#121215',
        'surface-dim': '#0d0d10',
        'surface-bright': '#27272a',
        'surface-container-lowest': '#09090b',
        'surface-container-low': '#141418',
        'surface-container': '#18181c',
        'surface-container-high': '#222227',
        'surface-container-highest': '#2a2a30',
        'on-surface': '#f4f4f5',
        'on-surface-variant': '#a1a1aa',
        'inverse-surface': '#f4f4f5',
        'inverse-on-surface': '#18181b',
        'outline': '#71717a',
        'outline-variant': '#3f3f46',
        'surface-tint': '#10b981',
        'primary': '#10b981',
        'on-primary': '#042f2e',
        'primary-container': '#059669',
        'on-primary-container': '#ecfdf5',
        'inverse-primary': '#34d399',
        'secondary': '#06b6d4',
        'on-secondary': '#083344',
        'secondary-container': '#0e7490',
        'on-secondary-container': '#cffafe',
        'tertiary': '#f59e0b',
        'on-tertiary': '#451a03',
        'tertiary-container': '#d97706',
        'on-tertiary-container': '#fef3c7',
        'error': '#f87171',
        'on-error': '#450a0a',
        'error-container': '#dc2626',
        'on-error-container': '#fee2e2',
        'background': '#09090b',
        'on-background': '#f4f4f5',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        body: ['Inter', 'sans-serif'],
        telemetry: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        'DEFAULT': '0.375rem',
        'sm': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
    },
  },
  plugins: [],
}

